# Generated by Django 5.1.1 on 2024-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topshiriq1", "0002_alter_account_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="active",
        ),
        migrations.AddField(
            model_name="account",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
